use crate::model::{FunctionBuildDefinition, LayerBuildDefinition};
use crate::planning::{
    compare_hash_changes_for_functions, compare_hash_changes_for_layers, HashUpdate,
};
use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::Path;

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct BuildGraph {
    #[serde(default)]
    pub function_build_definitions: Vec<FunctionBuildDefinition>,
    #[serde(default)]
    pub layer_build_definitions: Vec<LayerBuildDefinition>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct PersistedBuildGraph {
    #[serde(default)]
    function_build_definitions: toml::Table,
    #[serde(default)]
    layer_build_definitions: toml::Table,
}

impl BuildGraph {
    pub fn put_function_build_definition(
        &mut self,
        mut definition: FunctionBuildDefinition,
        function_full_path: impl Into<String>,
    ) {
        let function_full_path = function_full_path.into();
        if let Some(existing) = self
            .function_build_definitions
            .iter_mut()
            .find(|existing| existing.equivalent_for_build(&definition))
        {
            existing.add_function(function_full_path);
        } else {
            definition.add_function(function_full_path);
            self.function_build_definitions.push(definition);
        }
    }

    pub fn put_layer_build_definition(
        &mut self,
        mut definition: LayerBuildDefinition,
        layer_full_path: impl Into<String>,
    ) {
        let layer_full_path = layer_full_path.into();
        if let Some(existing) = self
            .layer_build_definitions
            .iter_mut()
            .find(|existing| existing.equivalent_for_build(&definition))
        {
            existing.layer = layer_full_path;
        } else {
            definition.layer = layer_full_path;
            self.layer_build_definitions.push(definition);
        }
    }

    pub fn read(path: impl AsRef<Path>) -> io::Result<Self> {
        let path = path.as_ref();
        let text = match fs::read_to_string(path) {
            Ok(text) => text,
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(error) => return Err(error),
        };
        let persisted: PersistedBuildGraph = toml::from_str(&text)
            .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;

        let function_build_definitions = persisted
            .function_build_definitions
            .into_iter()
            .map(|(uuid, value)| from_table_with_uuid(uuid, value))
            .collect::<Result<Vec<_>, _>>()?;
        let layer_build_definitions = persisted
            .layer_build_definitions
            .into_iter()
            .map(|(uuid, value)| from_table_with_uuid(uuid, value))
            .collect::<Result<Vec<_>, _>>()?;

        Ok(Self {
            function_build_definitions,
            layer_build_definitions,
        })
    }

    pub fn write(&self, path: impl AsRef<Path>) -> io::Result<()> {
        let mut persisted = PersistedBuildGraph::default();
        for definition in &self.function_build_definitions {
            persisted.function_build_definitions.insert(
                definition.uuid.clone(),
                toml::Value::try_from(definition)
                    .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?,
            );
        }
        for definition in &self.layer_build_definitions {
            persisted.layer_build_definitions.insert(
                definition.uuid.clone(),
                toml::Value::try_from(definition)
                    .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?,
            );
        }

        let mut text = String::from("# This file is auto generated by SAM CLI build command\n");
        text.push_str(
            &toml::to_string(&persisted)
                .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?,
        );
        fs::write(path, text)
    }

    pub fn clean_redundant_definitions(&mut self) {
        self.function_build_definitions
            .retain(|definition| !definition.functions.is_empty());
        self.layer_build_definitions
            .retain(|definition| !definition.layer.is_empty());
    }

    pub fn clean_redundant_definitions_and_write(
        &mut self,
        path: impl AsRef<Path>,
    ) -> io::Result<()> {
        self.clean_redundant_definitions();
        self.write(path)
    }

    pub fn write_hash_updates(
        &self,
        path: impl AsRef<Path>,
        function_updates: &std::collections::BTreeMap<String, HashUpdate>,
        layer_updates: &std::collections::BTreeMap<String, HashUpdate>,
    ) -> io::Result<()> {
        let path = path.as_ref();
        let mut persisted = Self::read(path)?;

        for definition in &mut persisted.function_build_definitions {
            if let Some(update) = function_updates.get(&definition.uuid) {
                definition.source_hash = update.source_hash.clone();
                definition.manifest_hash = update.manifest_hash.clone();
            }
        }
        for definition in &mut persisted.layer_build_definitions {
            if let Some(update) = layer_updates.get(&definition.uuid) {
                definition.source_hash = update.source_hash.clone();
                definition.manifest_hash = update.manifest_hash.clone();
            }
        }

        persisted.write(path)
    }

    pub fn update_definition_hashes(&mut self, path: impl AsRef<Path>) -> io::Result<()> {
        let mut persisted = Self::read(path.as_ref())?;
        let function_updates = compare_hash_changes_for_functions(
            &self.function_build_definitions,
            &mut persisted.function_build_definitions,
        );
        let layer_updates = compare_hash_changes_for_layers(
            &self.layer_build_definitions,
            &mut persisted.layer_build_definitions,
        );

        if !function_updates.is_empty() || !layer_updates.is_empty() {
            self.write_hash_updates(path, &function_updates, &layer_updates)?;
        }

        Ok(())
    }
}

fn from_table_with_uuid<T>(uuid: String, value: toml::Value) -> io::Result<T>
where
    T: for<'de> Deserialize<'de> + UuidField,
{
    let mut definition: T = value
        .try_into()
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    definition.set_uuid(uuid);
    Ok(definition)
}

trait UuidField {
    fn set_uuid(&mut self, uuid: String);
}

impl UuidField for FunctionBuildDefinition {
    fn set_uuid(&mut self, uuid: String) {
        self.uuid = uuid;
    }
}

impl UuidField for LayerBuildDefinition {
    fn set_uuid(&mut self, uuid: String) {
        self.uuid = uuid;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{EnvVars, Metadata, ZIP};
    use tempfile::tempdir;

    fn function(uuid: &str) -> FunctionBuildDefinition {
        FunctionBuildDefinition {
            uuid: uuid.into(),
            runtime: Some("python3.12".into()),
            codeuri: Some("src".into()),
            imageuri: None,
            packagetype: ZIP.into(),
            architecture: "x86_64".into(),
            metadata: Metadata::new(),
            handler: "app.handler".into(),
            source_hash: "source".into(),
            manifest_hash: "manifest".into(),
            env_vars: EnvVars::new(),
            functions: vec![],
            download_dependencies: true,
        }
    }

    #[test]
    fn dedupes_equivalent_functions() {
        let mut graph = BuildGraph::default();
        graph.put_function_build_definition(function("a"), "A");
        graph.put_function_build_definition(function("b"), "B");
        assert_eq!(graph.function_build_definitions.len(), 1);
        assert_eq!(
            graph.function_build_definitions[0].functions,
            vec!["A", "B"]
        );
    }

    #[test]
    fn round_trips_build_graph_toml() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("build.toml");
        let mut graph = BuildGraph::default();
        graph.put_function_build_definition(function("a"), "Stack/Fn");
        graph.write(&path).unwrap();

        let loaded = BuildGraph::read(&path).unwrap();
        assert_eq!(loaded.function_build_definitions.len(), 1);
        assert_eq!(loaded.function_build_definitions[0].uuid, "a");
        assert_eq!(
            loaded.function_build_definitions[0].functions,
            vec!["Stack/Fn"]
        );
    }

    #[test]
    fn reads_python_build_graph_layout() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("build.toml");
        std::fs::write(
            &path,
            r#"
            [function_build_definitions]
            [function_build_definitions.3c1c254e-cd4b-4d94-8c74-7ab870b36063]
            codeuri = "hello_world_python/"
            runtime = "python3.8"
            source_hash = "cae49aa393d669e850bd49869905099d"
            manifest_hash = "rty87gh393d669e850bd49869905099e"
            packagetype = "Zip"
            architecture = "arm64"
            handler = "app.handler"
            functions = ["HelloWorldPython", "HelloWorld2Python"]
            [function_build_definitions.3c1c254e-cd4b-4d94-8c74-7ab870b36063.metadata]
            Test = "hello"

            [layer_build_definitions]
            [layer_build_definitions.7dnc257e-cd4b-4d94-8c74-7ab870b3abc3]
            layer_name = "SumLayer"
            codeuri = "sum_layer/"
            build_method = "nodejs20.x"
            compatible_runtimes = ["nodejs20.x"]
            architecture = "x86_64"
            source_hash = "cae49aa393d669e850bd49869905099d"
            manifest_hash = "rty87gh393d669e850bd49869905099e"
            layer = "SumLayer"
            "#,
        )
        .unwrap();

        let graph = BuildGraph::read(&path).unwrap();
        assert_eq!(
            graph.function_build_definitions[0].uuid,
            "3c1c254e-cd4b-4d94-8c74-7ab870b36063"
        );
        assert_eq!(
            graph.function_build_definitions[0].runtime.as_deref(),
            Some("python3.8")
        );
        assert_eq!(graph.layer_build_definitions[0].layer_name, "SumLayer");
    }

    #[test]
    fn cleans_redundant_definitions_before_write() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("build.toml");
        let mut graph = BuildGraph {
            function_build_definitions: vec![function("empty"), {
                let mut retained = function("retained");
                retained.functions = vec!["Fn".into()];
                retained
            }],
            layer_build_definitions: vec![],
        };

        graph.clean_redundant_definitions_and_write(&path).unwrap();
        let loaded = BuildGraph::read(&path).unwrap();
        assert_eq!(loaded.function_build_definitions.len(), 1);
        assert_eq!(loaded.function_build_definitions[0].uuid, "retained");
    }

    #[test]
    fn updates_only_hashes_for_partial_builds() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("build.toml");
        let mut persisted = BuildGraph::default();
        persisted.put_function_build_definition(function("same"), "Fn");
        persisted.write(&path).unwrap();

        let mut current = BuildGraph::default();
        let mut updated = function("same");
        updated.source_hash = "new-source".into();
        updated.manifest_hash = "new-manifest".into();
        current.put_function_build_definition(updated, "Fn");
        current.update_definition_hashes(&path).unwrap();

        let loaded = BuildGraph::read(&path).unwrap();
        assert_eq!(
            loaded.function_build_definitions[0].source_hash,
            "new-source"
        );
        assert_eq!(
            loaded.function_build_definitions[0].manifest_hash,
            "new-manifest"
        );
        assert_eq!(current.function_build_definitions[0].functions, vec!["Fn"]);
    }
}
