use serde::Serialize;
use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;
use time::format_description::well_known::Iso8601;
use time::OffsetDateTime;

#[derive(Clone, Debug, Serialize)]
pub struct SyncStateDocument {
    pub sync_state: SyncStateSection,
    pub resource_sync_states: BTreeMap<String, ResourceSyncStateSection>,
}

#[derive(Clone, Debug, Serialize)]
pub struct SyncStateSection {
    pub dependency_layer: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latest_infra_sync_time: Option<f64>,
}

#[derive(Clone, Debug, Serialize)]
pub struct ResourceSyncStateSection {
    pub hash: String,
    pub sync_time: f64,
}

pub fn write_sync_state(path: impl AsRef<Path>, state: &SyncStateDocument) -> io::Result<()> {
    let mut content = String::from("# This file is auto generated by SAM CLI sync command\n");
    content.push_str(
        &toml::to_string(state)
            .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error.to_string()))?,
    );
    fs::write(path, content)
}

#[derive(Clone, Debug)]
pub struct ParsedSyncState {
    pub dependency_layer: bool,
    pub latest_infra_sync_time: Option<f64>,
    pub resource_sync_states: Vec<(String, String, f64)>,
}

pub fn read_sync_state(path: impl AsRef<Path>) -> io::Result<Option<ParsedSyncState>> {
    let content = match fs::read_to_string(path) {
        Ok(content) => content,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    let document = content
        .parse::<toml::Table>()
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error.to_string()))?;

    let sync_state = document.get("sync_state").and_then(toml::Value::as_table);
    let resources = document
        .get("resource_sync_states")
        .and_then(toml::Value::as_table);
    if sync_state.is_none() && resources.is_none() {
        return Ok(None);
    }

    let dependency_layer = sync_state
        .and_then(|table| table.get("dependency_layer"))
        .and_then(toml::Value::as_bool)
        .unwrap_or(false);
    let latest_infra_sync_time = sync_state
        .and_then(|table| table.get("latest_infra_sync_time"))
        .and_then(parse_timestamp);

    let mut resource_sync_states = Vec::new();
    if let Some(resources) = resources {
        for (resource_id, value) in resources {
            let Some(table) = value.as_table() else {
                continue;
            };
            let Some(hash) = table.get("hash").and_then(toml::Value::as_str) else {
                continue;
            };
            let Some(sync_time) = table.get("sync_time").and_then(parse_timestamp) else {
                continue;
            };
            resource_sync_states.push((resource_id.replace('-', "/"), hash.to_string(), sync_time));
        }
    }

    Ok(Some(ParsedSyncState {
        dependency_layer,
        latest_infra_sync_time,
        resource_sync_states,
    }))
}

fn parse_timestamp(value: &toml::Value) -> Option<f64> {
    match value {
        toml::Value::Integer(value) => Some(*value as f64),
        toml::Value::Float(value) => Some(*value),
        toml::Value::Datetime(value) => {
            OffsetDateTime::parse(&value.to_string(), &Iso8601::DEFAULT)
                .ok()
                .map(|value| {
                    value.unix_timestamp() as f64 + value.nanosecond() as f64 / 1_000_000_000.0
                })
        }
        toml::Value::String(value) => {
            let normalized = if value.ends_with('Z') {
                value.clone()
            } else if value.contains('+') || value.rfind('-').is_some_and(|index| index > 9) {
                value.clone()
            } else {
                format!("{value}Z")
            };
            OffsetDateTime::parse(&normalized, &Iso8601::DEFAULT)
                .ok()
                .map(|value| {
                    value.unix_timestamp() as f64 + value.nanosecond() as f64 / 1_000_000_000.0
                })
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn reads_mixed_timestamp_formats_and_skips_invalid_rows() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("sync.toml");
        fs::write(
            &path,
            r#"
[sync_state]
dependency_layer = true
latest_infra_sync_time = 1733267411.916279

[resource_sync_states.Valid]
hash = "valid"
sync_time = "2025-12-03T22:10:35.345701"

[resource_sync_states.Invalid]
hash = "invalid"
sync_time = "bad"
"#,
        )
        .unwrap();

        let state = read_sync_state(path).unwrap().unwrap();
        assert!(state.dependency_layer);
        assert_eq!(state.resource_sync_states.len(), 1);
        assert_eq!(state.resource_sync_states[0].0, "Valid");
    }
}
